---
abstract: 'Pure Perl simple message bus'
author:
  - 'Horea Gligan <horea@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-MessageBus
no_index:
  directory:
    - t
    - inc
requires:
  Class::Accessor: 0
  IO::Select: 0
  IO::Socket::INET: 0
  JSON: 0
  Log::Log4perl: 0
  Test::More: 0
version: 0.03
