--- #YAML:1.0
name:               Net-MessageBus
version:            0.06
abstract:           Pure Perl simple message bus
author:
    - Horea Gligan <horea@gmail.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Class::Accessor:   0
    IO::Select:        0
    IO::Socket::INET:  0
    JSON:              0
    Log::Log4perl:     0
    Test::More:        0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
